### ISSUE TITLE
 databricks

### ISSUE THREAD

**Issue by Yoga096** [yukiregista/DSC_STUDY#5]
#  Databricks
## Todo
- [ ] Azure Databricksへログイン

## リンク
- クラウド版
（[利用方法の参考URL](https://ketanadocshare.blob.core.windows.net/share01/FDUA_%E7%AC%AC2%E5%9B%9E_%E9%87%91%E8%9E%8D%E3%83%87%E3%83%BC%E3%82%BF%E6%B4%BB%E7%94%A8%E3%83%81%E3%83%A3%E3%83%AC%E3%83%B3%E3%82%B8.pdf?sv=2022-11-02&ss=bfqt&srt=sco&sp=rlx&se=2024-03-31T11:20:14Z&st=2024-01-16T03:20:14Z&spr=https,http&sig=e1eERzb%2FcZ35URm%2BOgVGjAiQPm355zobyM0gyv8j7fo%3D)）
- [製品概要](https://www.databricks.com/jp/product/data-intelligence-platform)
- [導入事例](https://www.databricks.com/jp/customers)
- [Global金融事例](https://www.databricks.com/jp/solutions/industries/financial-services)

**Comment by Yoga096** [comment]
# シナリオ（一旦放置中）

## 事前準備
 - [ ] データダウンロード
 - [ ] Notebookダウンロード

## 1. ターゲット顧客を抽出
 - [ ] データをアップロード
 - [ ] データの可視化(ダッシュボード) (時間かかすぎで一旦辞めます)
 - [ ] 初歩的分析
 - [ ] ユーザーの顧客生涯価値をスコアリング（執行 CLV_Part1_CustomerLifetime）
 - [ ] ダッシュボードでターゲットユーザーを抽出
 - [ ] 過程、結果の記録

## 2. 分析過程の自動化
 - [ ] リアルタイムでトランザクションデータを蓄積
 - [ ] スコアリングを定期的に実行できるように
 - [ ] 利用状況をリアルタイムで可視化
 - [ ] 顧客の抽出過程をジョブで自動化

## 3. データとAIのガバナンス
 - [ ] データ権限・リネージュ管理
 - [ ] ダッシュボード権限管理
 - [ ] AIモデル実験・バージョン・権限管理
 - [ ] データカタログを用いて、非構造化データの管理
 - [ ] Power BIと接続
 - [ ] グローバルデーガバナンス

**Comment by Yoga096** [comment]
# 自分のNoteBookで作業
 - [ ] 自分のNoteBook作成 ![image](https://github.com/yukiregista/DSC_STUDY/assets/46023776/e8a74ff6-ab97-41bc-9816-29096ccfaf04)
 - [ ] データ用のフォルダーを作成 ![image](https://github.com/yukiregista/DSC_STUDY/assets/46023776/4dbed4f5-83a3-4123-b6cf-f9d7348b845b)
 - [ ] データをアップロード ![image](https://github.com/yukiregista/DSC_STUDY/assets/46023776/805a1dc0-e792-4291-baf9-ae866ae21eb2)
 - [ ] 自分のNoteBookでデータを読み込む ![image](https://github.com/yukiregista/DSC_STUDY/assets/46023776/c50dec3b-6d3c-425a-91d7-bc7605fd850d) 
![image](https://github.com/yukiregista/DSC_STUDY/assets/46023776/3c135aca-685e-4edb-9926-e342ed852964)
